version: 2

jobs:
  testing:
    docker:
      - image: massiveco/docker-alpine-sdk
    steps:
      - checkout
      - run: sudo apk update
      - run: make testing
      - persist_to_workspace:
          root: /tmp
          paths:
            - packages
  stable:
    docker:
      - image: massiveco/docker-alpine-sdk
    steps:
      - checkout
      - run: sudo apk update
      - run: make stable
      - persist_to_workspace:
          root: /tmp
          paths:
            - packages
  deploy:
    docker:
      - image: alpine:3.7
    steps:
      - attach_workspace:
          at: /tmp/
      - run: echo DEPLOY!!
      # - run: echo $SSH_PRIV_KEY | base64 -D > .ssh/circleci
      # - run: apk --update add rsync
      # - run: rsync -avrz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress /tmp/packages alpine.ma.ssive.co:/var/www/alpine.ma.ssive.co/


workflows:
  version: 2
  build_all_packages:
    jobs:
      - testing
      - stable
      - deploy:
          requires:
              - testing
              - stable