version: 2
jobs:
  packages:
    docker:
      - image: massiveco/docker-alpine-sdk
    steps:
      - checkout
      - run: make all
      - store_artifacts:
          path: /tmp/packages
workflows:
  version: 2
  build_and_test:
    jobs:
      - packages