version: 2
jobs:
  build:
    docker:
      - image: massiveco/docker-alpine-sdk
    steps:
      - checkout
      - run: make testing
      - store_artifacts:
          path: /tmp/packages
  stable:
    docker:
      - image: massiveco/docker-alpine-sdk
    steps:
      - checkout
      - run: make stable
      - store_artifacts:
          path: /tmp/packages
workflows:
  version: 2
  build:
    jobs:
      - build
      - stable