version: 2

jobs:
  testing:
    docker:
      - image: massiveco/docker-alpine-sdk
    steps:
      - checkout
      - run: make testing
      - store_artifacts:
          path: /tmp/packages
  stable:
    docker:
      - image: massiveco/docker-alpine-sdk
    steps:
      - checkout
      - run: make stable
      - store_artifacts:
          path: /tmp/packages
  deploy:
    docker:
      - image: massiveco/docker-alpine-sdk
    steps:
      - run: echo Hello World!

workflows:
  version: 2
  build:
    jobs:
      - build
      - stable
      - deploy:
          requires:
              - testing
              - stable